###############################################################################
# Created by write_sdc
# Mon Nov  6 02:07:33 2023
###############################################################################
current_design top_ew_algofoogle
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name i_clk -period 38.0000 [get_ports {i_clk}]
set_clock_transition 0.1500 [get_clocks {i_clk}]
set_clock_uncertainty 0.2500 i_clk
set_propagated_clock [get_clocks {i_clk}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_debug_map_overlay}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_debug_trace_overlay}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_debug_vec_overlay}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout0_sel[0]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout0_sel[1]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout0_sel[2]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout0_sel[3]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout0_sel[4]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout0_sel[5]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout1_sel[0]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout1_sel[1]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout1_sel[2]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout1_sel[3]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout1_sel[4]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout1_sel[5]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout2_sel[0]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout2_sel[1]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout2_sel[2]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout2_sel[3]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout2_sel[4]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout2_sel[5]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout3_sel[0]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout3_sel[1]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout3_sel[2]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout3_sel[3]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout3_sel[4]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout3_sel[5]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout4_sel[0]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout4_sel[1]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout4_sel[2]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout4_sel[3]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout4_sel[4]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout4_sel[5]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout5_sel[0]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout5_sel[1]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout5_sel[2]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout5_sel[3]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout5_sel[4]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_gpout5_sel[5]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_la_invalid}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode[0]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode[1]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_mode[2]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_csb}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_mosi}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_outs_enb}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reg_sclk}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reset_lock_a}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_reset_lock_b}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_spare_0}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_spare_1}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_test_uc2}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_test_wci}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_tex_in[0]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_tex_in[1]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_tex_in[2]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_tex_in[3]}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_vec_csb}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_vec_mosi}]
set_input_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {i_vec_sclk}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_gpout[0]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_gpout[1]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_gpout[2]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_gpout[3]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_gpout[4]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_gpout[5]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_hsync}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_reset}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[0]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[10]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[11]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[12]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[13]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[14]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[15]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[16]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[17]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[18]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[19]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[1]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[20]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[21]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[22]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[23]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[2]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[3]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[4]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[5]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[6]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[7]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[8]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_rgb[9]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_tex_csb}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_tex_oeb0}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_tex_out0}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_tex_sclk}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {o_vsync}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[0]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[10]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[11]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[12]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[13]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[14]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[15]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[1]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[2]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[3]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[4]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[5]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[6]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[7]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[8]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {ones[9]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[0]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[10]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[11]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[12]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[13]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[14]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[15]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[1]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[2]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[3]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[4]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[5]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[6]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[7]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[8]}]
set_output_delay 7.6000 -clock [get_clocks {i_clk}] -add_delay [get_ports {zeros[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {o_hsync}]
set_load -pin_load 0.0334 [get_ports {o_reset}]
set_load -pin_load 0.0334 [get_ports {o_tex_csb}]
set_load -pin_load 0.0334 [get_ports {o_tex_oeb0}]
set_load -pin_load 0.0334 [get_ports {o_tex_out0}]
set_load -pin_load 0.0334 [get_ports {o_tex_sclk}]
set_load -pin_load 0.0334 [get_ports {o_vsync}]
set_load -pin_load 0.0334 [get_ports {o_gpout[5]}]
set_load -pin_load 0.0334 [get_ports {o_gpout[4]}]
set_load -pin_load 0.0334 [get_ports {o_gpout[3]}]
set_load -pin_load 0.0334 [get_ports {o_gpout[2]}]
set_load -pin_load 0.0334 [get_ports {o_gpout[1]}]
set_load -pin_load 0.0334 [get_ports {o_gpout[0]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[23]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[22]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[21]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[20]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[19]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[18]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[17]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[16]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[15]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[14]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[13]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[12]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[11]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[10]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[9]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[8]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[7]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[6]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[5]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[4]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[3]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[2]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[1]}]
set_load -pin_load 0.0334 [get_ports {o_rgb[0]}]
set_load -pin_load 0.0334 [get_ports {ones[15]}]
set_load -pin_load 0.0334 [get_ports {ones[14]}]
set_load -pin_load 0.0334 [get_ports {ones[13]}]
set_load -pin_load 0.0334 [get_ports {ones[12]}]
set_load -pin_load 0.0334 [get_ports {ones[11]}]
set_load -pin_load 0.0334 [get_ports {ones[10]}]
set_load -pin_load 0.0334 [get_ports {ones[9]}]
set_load -pin_load 0.0334 [get_ports {ones[8]}]
set_load -pin_load 0.0334 [get_ports {ones[7]}]
set_load -pin_load 0.0334 [get_ports {ones[6]}]
set_load -pin_load 0.0334 [get_ports {ones[5]}]
set_load -pin_load 0.0334 [get_ports {ones[4]}]
set_load -pin_load 0.0334 [get_ports {ones[3]}]
set_load -pin_load 0.0334 [get_ports {ones[2]}]
set_load -pin_load 0.0334 [get_ports {ones[1]}]
set_load -pin_load 0.0334 [get_ports {ones[0]}]
set_load -pin_load 0.0334 [get_ports {zeros[15]}]
set_load -pin_load 0.0334 [get_ports {zeros[14]}]
set_load -pin_load 0.0334 [get_ports {zeros[13]}]
set_load -pin_load 0.0334 [get_ports {zeros[12]}]
set_load -pin_load 0.0334 [get_ports {zeros[11]}]
set_load -pin_load 0.0334 [get_ports {zeros[10]}]
set_load -pin_load 0.0334 [get_ports {zeros[9]}]
set_load -pin_load 0.0334 [get_ports {zeros[8]}]
set_load -pin_load 0.0334 [get_ports {zeros[7]}]
set_load -pin_load 0.0334 [get_ports {zeros[6]}]
set_load -pin_load 0.0334 [get_ports {zeros[5]}]
set_load -pin_load 0.0334 [get_ports {zeros[4]}]
set_load -pin_load 0.0334 [get_ports {zeros[3]}]
set_load -pin_load 0.0334 [get_ports {zeros[2]}]
set_load -pin_load 0.0334 [get_ports {zeros[1]}]
set_load -pin_load 0.0334 [get_ports {zeros[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_debug_map_overlay}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_debug_trace_overlay}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_debug_vec_overlay}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_la_invalid}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_csb}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_mosi}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_outs_enb}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reg_sclk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reset_lock_a}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_reset_lock_b}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_spare_0}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_spare_1}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_test_uc2}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_test_wci}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_vec_csb}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_vec_mosi}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_vec_sclk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout0_sel[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout0_sel[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout0_sel[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout0_sel[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout0_sel[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout0_sel[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout1_sel[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout1_sel[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout1_sel[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout1_sel[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout1_sel[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout1_sel[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout2_sel[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout2_sel[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout2_sel[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout2_sel[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout2_sel[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout2_sel[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout3_sel[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout3_sel[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout3_sel[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout3_sel[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout3_sel[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout3_sel[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout4_sel[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout4_sel[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout4_sel[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout4_sel[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout4_sel[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout4_sel[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout5_sel[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout5_sel[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout5_sel[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout5_sel[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout5_sel[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_gpout5_sel[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_mode[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_tex_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_tex_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_tex_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {i_tex_in[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
